pipeline {
    agent {
        docker {
            image 'python:3.10'
        }
    }
    parameters {
        choice(name: 'REPO_NAME', choices: ['fe', 'be'], description: 'Select the repository to build')
    }
    environment {
        DOCKERHUB_CREDENTIALS = credentials('1')
        DOCKER_REGISTRY = 'amit142'
        IMAGE_TAG = "${env.BUILD_NUMBER}"
        DOCKERFILE_PATH = "exam-code/docker/${params.REPO_NAME}"  // Define the Dockerfile path based on the selected repo
    }
    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'workshop/argo-jenkins-exam', url: 'https://github.com/amit142/devopshift-welcome.git'
            }
        }

        stage('Lint & Security Scan') {
            steps {
                sh 'apt install python3-pip flake8 bandit'
                sh 'flake8 .'
                sh 'bandit -r .'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'pip install -r requirements.txt'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    // Build the Docker image based on the selected repo (frontend or backend)
                    sh "docker build -t $DOCKER_REGISTRY/$params.REPO_NAME:$IMAGE_TAG -f $DOCKERFILE_PATH/Dockerfile ."
                    sh "docker tag $DOCKER_REGISTRY/$params.REPO_NAME:$IMAGE_TAG $DOCKER_REGISTRY/$params.REPO_NAME:latest"
                }
            }
        }

        stage('Run Tests in Container') {
            steps {
                script {
                    // Running the tests within the Docker container
                    sh "docker run --rm $DOCKER_REGISTRY/$params.REPO_NAME:$IMAGE_TAG pytest tests/"
                }
            }
        }

        stage('Integration Test with Docker Compose') {
            steps {
                script {
                    sh 'docker-compose -f $DOCKERFILE_PATH/docker-compose.yml up -d'
                    sleep time: 10, unit: 'SECONDS'  // Wait for services to start
                    sh 'curl -f http://localhost:5002 || exit 1'  // Adjust port for backend if needed
                    sh 'docker-compose down'
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                script {
                    // Login and push to Docker Hub
                    sh "echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin"
                    sh "docker push $DOCKER_REGISTRY/$params.REPO_NAME:$IMAGE_TAG"
                    sh "docker push $DOCKER_REGISTRY/$params.REPO_NAME:latest"
                }
            }
        }
    }
}
